### ISSUE TITLE
Custom Play/Pause Highlight Colours do not persist through a refresh.

### ISSUE THREAD

**Issue by XtraButtery** [Mallander/playlist-enhancer#12]
Foundry 0.8.8
Playlist Enhancer 1.1.2

After refreshing the page the entries for "Playing" and "Paused" "playlist/song highlight color" are ignored and default back to the default colour scheme (which is also not friendly/accessible to users with visual impairments)

The default colours will persist until the custom colours are changed within the settings, even when the setting is not set to the default value. Refreshing the page will once again cause the issue to revert.

This bug has been tested and observed in both Chromium and Firefox based browsers.

**Comment by Mallander** [comment]
Thanks for raising! I'll take a look and resolve this for you as well as revising the default colours to ensure they're usable for everyone.

**Comment by XtraButtery** [comment]
In my usual game I use another UI mod so the colours differ slightly but I primarily use
#FFFF00 as the playing colour and #999999 as the paused colour.

But I think a better _standard_ colour scheme might be #ffaa00 as the playing colour and #999999 for paused.

Orange is used in Foundry's UI quite a lot so it makes sense to use it as the active track indicator, and that particular shade of orange is just bright enough to be accessible to virtually anyone (even those who are visually impaired)

For the paused indicator a greyed out or darker version of the default white text is both legible enough (especially as the name of the track is displayed near the top of the screen as well in clear white) and is widely recognised to mean inactive or inert while the obvious difference will make it clear to any user that the track is indeed selected.

As a general rule of thumb for creating colour schemes involving the colour of text I try to follow the WCAG (Web Content Accessibility Guidelines) standards. Since your text is rather small you should be aiming for a AAA Pass for Normal Text (which you can easily check using this website:
https://colourcontrast.cc/24282a/ffaa00

I'm using #24282a as the background colour because while Foundry's default background changes slightly due to transparency effects this is the colour of the background against the default scene grey, which should provide enough of an average result to be more-or-less accurate for most users.

Hope this helps!

**Comment by Mallander** [comment]
That's brilliant feedback, thank you!

I should be looking at releasing an amended version early next week with the fix applied and a new colour scheme in place.

**Comment by Mallander** [comment]
Thanks for all your feedback on this issue and advising the new default colours, I liked them for the defaults so have stuck with your suggestions!

I've just released a new version of the module that's now available with the bug fixed and the new defaults in place.
