### ISSUE TITLE
Drag and Drop between playlists broke under Foundry V9

### ISSUE THREAD

**Issue by Lexaj-dev** [Mallander/playlist-enhancer#14]
ever since updating to Foundry V9 my playlist enhancement don't work properly anymore, namely the drag and drop.

**Comment by Mallander** [comment]
Thanks,

I've not updated to support V9 yet, that will be coming this weekend so keep an eye out

**Comment by Joshmvii7** [comment]
Hi. Just wondering if V9 support is still coming for this? The bulk editing of playlists isn't working for me on v9. Thanks!

**Comment by RiotGoesWoof** [comment]
Hey there! Love the add-on? Any update on this?

Also to add a workaround, you can drag from the "Currently Playing" List and it will still copy that way.

**Comment by Mallander** [comment]
Hi all,

Life is getting in the way a little at the moment, I was hoping to have the V9 update out much sooner! I'll take a look tomorrow and try to get a functional version ready for you all!

Mallander

**Comment by RiotGoesWoof** [comment]
Not a problem, thank you for the quick response!! 💙

**Comment by Joshmvii7** [comment]
Thanks so much for updating this and the notification!
