### ISSUE TITLE
Conflict with Maestro

### ISSUE THREAD

**Issue by apoapostolov** [Mallander/playlist-enhancer#2]
Maestro mod will show this button in the Playlist Enhancer. 

Also, but it is very minor, the button with the Combine action doesn't have a centered icon in it. 

![image](https://user-images.githubusercontent.com/4083812/122811209-da2bbb00-d2d8-11eb-8d71-d47230586b0d.png)

**Comment by Mallander** [comment]
Thanks @apoapostolov - I'll take a look and see if I can get them both working together properly.

The "Curate" button should have wording on it next to the icon which I don't think it visible with Maestro installed so I'll check it out

**Comment by Mallander** [comment]
Fixed in latest release
