### ISSUE TITLE
New idea - color for playing / paused sounds different than white

### ISSUE THREAD

**Issue by apoapostolov** [Mallander/playlist-enhancer#4]
This will greatly help to find the currently playing or playing but paused songs

Custom color for the songs and their folders and playlists (containing them) that have currently playing songs.

For example:
* Green for playing song
* Light Green for the text of the folder and playlist containing playing songs
* Yellow for playing but paused song
* Light Yellow for the text of the folder and playlist containing playing songs

With settings to set desired colors.

**Comment by Mallander** [comment]
Awesome idea @apoapostolov - keep them coming!

**Comment by Mallander** [comment]
Added in the latest release including:

Settings options to enable/disable on preference
Settings to choose the highlight colours so it can fit with any theme
