### ISSUE TITLE
Improved Loop

### ISSUE THREAD

**Issue by apoapostolov** [Mallander/playlist-enhancer#8]
This is a pretty complex feature and I would totally understand if it is out of scope for this mod.

A typical fantasy score music has parts that are not fit for a loop during combat. They start with a mellow buildup, then hit the dynamic battle theme, then often have a slow downhill end. Due to this, looping that sound would be constantly entering mellow buildups for half a minute of battle theme, so on and so forth. 

Thanks to the new audio API the following may be possible:
* Each track gets two new time parameters in milliseconds - loop start and loop end time.
* When a track reaches the loop end - the fade duration, it starts to fade into the loop start.

Example: A 00:60.000 combat melody has a buildup from 00:00.000 to 00:34.230, then blasts epic battle from 00:34.240 until 00:54.000. it also has a 00:06.000 (12000ms) fade. The user, listening to the song, sets the loop start at 00:35.00 and the loop end at 00:54.000. When the song gets close to 00:54.000 - 00:06.000, it starts to fade into the same song that starts not from 00:00.000 but 00:35.000. This means that the slow ballad buildup will only be heard once, and the rest will be endless combat epicness until the theme is stopped.

Documentation: 
* https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/loopStart
* https://developer.mozilla.org/en-US/docs/Web/API/AudioBufferSourceNode/loopEnd

UI:
* This functionality will add two new fields to each song modal dialog, Loop Start (ms) and Loop End (ms). You may consider adding a "Forced Loop" checkbox that ignores the fields if turned off.

**Comment by Mallander** [comment]
An interesting feature, it wouldn't be out of scope for the module per-se but definitely a lot of work to implement.

But I'm up for giving it a go and a research

**Comment by apoapostolov** [comment]
Thank you for considering this. This would greatly improve the usability of the general "theme music" soundtracks usable for combat music.

**Comment by Mallander** [comment]
While investigating this on my side, a modeule developer has made something that does this for the League of Foundry Developer's package jam which may be worth a look:

https://github.com/CarterDC/track-tracker

I'm not sure on his future plans, but to avoid duplication of modules/work I'll park this on my side for now and look to fully support his module if it's to be continue post-jam.

**Comment by apoapostolov** [comment]
Thank you. I will post the same feature on his GitHub tracker and see if he can support it in the future.

**Comment by apoapostolov** [comment]
Just to let you know that I spoke with CarterDC and he liked the idea and its use cases, though no commitment yet, so it is okay to close this ticket here.

**Comment by Mallander** [comment]
Awesome, thanks for looping back! I've spoken to CarterDC about our module compatibility so we'll be working on making sure they work well together
