### ISSUE TITLE
Theme Announcer and Credits

### ISSUE THREAD

**Issue by apoapostolov** [Mallander/playlist-enhancer#9]
The purpose of this feature is to make specific music themes to be more prominent and important to the game by announcing them as Boss Themes, Location Themes, etc. Also, they help Twitch and YouTube streamers to properly credit music authors they have licensed from by showing credits without having to spell the music artist credit at the start of the stream

A new check option for each playlist sound called "Announce Theme", and three text fields named "Theme Name", "Original Title [optional]" and "Original Artist [optional]". When the "Announce Theme" is turned on, when the song starts playing, on the screen fades a beautiful theme name announcement, akin to MTV or other music televisions. For example, when the players meet Strahd and his ballad theme starts, the announcement in the bottom left corner of the canvas would show:

Line 1, large font: Strahd's Tragedy [in larger bold font, this is the relevant use of the sound theme]
Line 2, small font: Dark Gathering by Gothic Sounds [since the GM wants to credit the artist, for example on a Twitch stream] - this line is optional if Original Title and Original Artist have text in them. 

The announcement is in the bottom left corner of the canvas however in Settings the GM can use the Horizontal and Vertical Offset based on the bottom left corner of the screen to set the placement as he sees fit. Also, in order to set the visual style as he wants it using colors, web fonts, etc., the CSS class for the announcer should be exposed and editable in the Settings. 

Settings
* Placement Options
* * Horizontal Offset from Bottom Left Corner, measured in % of screen width
* * Vertical Offset from Bottom Left Corner, measured in % of screen height
* Announcement Time [in s] - default is 6
* Announcement Effect - no effect, fade in/out, slide in/out from the bottom, etc.
* CSS class textbox - allows power users to apply Google web fonts, special 

Behavior Cases:
* Theme Announcement should show on sound start, not sound resume
* Theme Announcement should not show again if sound paused/stopped, and then starts the same sound.

**Comment by Mallander** [comment]
I'd say this would be better as it's own module, If it's not already added to the League of Foundry Developers Trello request board I'd advise adding it there for visibility :)
